inn = open('/home/odonata/Projects/Address_Programm/Adressbuch.csv','r')

for line in inn.readlines():
    out = open('/home/odonata/Projects/Address_Programm/tester2/' + line.rsplit(',')[0] + ' ' + line.rsplit(',')[1] + '.vcf','w')
    out.write('BEGIN:VCARD' + '\r\n' + 'VERSION:3.0' + '\r\n')
    out.write('FN:' + line.rsplit(',')[0] + ' ' + line.rsplit(',')[1] + '\r\n')
    out.write('NOTE:' + line.rsplit(',')[2] + '\r\n')
    out.write('X-GENDER:'  + line.rsplit(',')[3] + '\r\n')
    out.write('ORG:' + line.rsplit(',')[4] + '\r\n')
    out.write('TITLE:'  + line.rsplit(',')[5] + '\r\n')
    out.write('NICKNAME:' + line.rsplit(',')[6] + '\r\n')
    out.write('URL:' + line.rsplit(',')[7] + '\r\n')
    out.write('ADR;TYPE=HOME:' + line.rsplit(',')[8] + '\r\n')
    out.write('ADR;TYPE=WORK:' + line.rsplit(',')[9] + '\r\n')
    out.write('ADR:' + line.rsplit(',')[10] + '\r\n')
    out.write('BDAY:' + line.rsplit(',')[11] + '\r\n')
    out.write('EMAIL:' + line.rsplit(',')[12] + '\r\n')
    out.write('EMAIL;TYPE=HOME:' + line.rsplit(',')[13] + '\r\n')
    out.write('EMAIL;TYPE=WORK:' + line.rsplit(',')[14] + '\r\n')
    out.write('TEL;TYPE=WORK,CELL:' + line.rsplit(',')[15] + '\r\n')
    out.write('TEL;TYPE=HOME,CELL:' + line.rsplit(',')[16] + '\r\n')
    out.write('TEL;TYPE=CELL:' + line.rsplit(',')[17] + '\r\n')
    out.write('TEL;TYPE=WORK,VOICE:' + line.rsplit(',')[18] + '\r\n')
    out.write('TEL;TYPE=HOME,VOICE:' + line.rsplit(',')[19] + '\r\n')
    out.write('TEL;TYPE=VOICE:' + line.rsplit(',')[20] + '\r\n')
    out.write('TEL;TYPE=FAX:' + line.rsplit(',')[21] + '\r\n')
    out.write('X-ICQ;TYPE=icq:' + line.rsplit(',')[22] + '\r\n')
    out.write('X-SKYPE;TYPE=skype:' + line.rsplit(',')[23] + '\r\n')
    out.write('X-SIP;TYPE=sip:' + line.rsplit(',')[24] + '\r\n')
    out.write('PHOTO;TYPE=png;ENCODING=b:' + line.rsplit(',')[25] + '\r\n')
    out.write('END:VCARD\r\n')
    out.close()
inn.close()

